# Generated by Django 5.2.1 on 2025-05-14 07:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="餐厅名称")),
                ("description", models.TextField(blank=True, verbose_name="餐厅描述")),
                ("address", models.CharField(max_length=200, verbose_name="地址")),
                ("phone", models.CharField(max_length=15, verbose_name="联系电话")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="restaurant_logos/",
                        verbose_name="餐厅标志",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否营业"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "餐厅",
                "verbose_name_plural": "餐厅",
            },
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="桌名/编号")),
                (
                    "seats",
                    models.PositiveSmallIntegerField(default=4, verbose_name="座位数"),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="table_qrcodes/",
                        verbose_name="二维码",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "餐桌",
                "verbose_name_plural": "餐桌",
            },
        ),
    ]
