# Generated by Django 5.0.1 on 2025-05-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, verbose_name="Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("restaurant", "Restaurant Owner"),
                    ("admin", "Administrator"),
                ],
                default="customer",
                max_length=10,
                verbose_name="User Type",
            ),
        ),
    ]
