# Generated by Django 5.2.1 on 2025-05-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                ("description", models.TextField(blank=True, verbose_name="分类描述")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
            ],
            options={
                "verbose_name": "菜品分类",
                "verbose_name_plural": "菜品分类",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="菜单名称")),
                ("description", models.TextField(blank=True, verbose_name="菜单描述")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "菜单",
                "verbose_name_plural": "菜单",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="菜品名称")),
                ("description", models.TextField(blank=True, verbose_name="菜品描述")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="menu_items/",
                        verbose_name="菜品图片",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="是否可点"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="是否推荐"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="排序"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "菜品",
                "verbose_name_plural": "菜品",
                "ordering": ["order", "id"],
            },
        ),
    ]
