# Generated by Django 5.2.1 on 2025-05-14 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to="restaurant.restaurant",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="table",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="carts",
                to="restaurant.table",
            ),
        ),
    ]
